import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },

];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "wraps",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des:"Elevate your style with Stimul Wraps—a seamless blend of modern design and comfort. These lightweight, easy-to-wear wraps feature a breathable fabric for all-day ease, making them perfect for casual outings, travel, or adding a trendy accent to any look. With a sleek black and white design, they offer effortless versatility and a touch of sophistication. A must-have accessory for those who value both style and convenience." },
  {
    _id: "202",
    img: newArrFour,
    productName: "Smart Water",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Pure hydration redefined. Our premium Smart Water bottle features nano-filtration technology that removes 99.9% of impurities while enriching water with essential minerals. The solar-charging cap displays real-time hydration stats and syncs with health apps to optimize your water intake based on activity levels. Sleek aerospace-grade aluminum construction keeps liquids cold for 24 hours.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Smart water Big",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Stay optimally hydrated with Smart Water the intelligent way to drink. Our eco-friendly smart bottle syncs with your fitness tracker to glow when it's time to hydrate and tracks your daily intake via app. The built-in fruit infuser and triple-filter system transform tap water into spa-quality infused water, while the ergonomic grip fits perfectly in car cup holders.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Smart Watch",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "More than timekeeping. This Smart Watch features a blood oxygen monitor, menstrual cycle tracker, and built-in GPS for under $100. The 2-week battery life and military-grade durability make it ideal for adventurers. Customize with 100+ downloadable watch faces.",
  },
];


export const paginationItems = [
  {
    _id: 1001,
    img: spfOne,
    productName: "wraps",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Timeless and versatile, these Black & White wraps are a wardrobe essential. The high-contrast design pairs effortlessly with any outfit, offering a sleek, modern aesthetic. Crafted from premium fabric, they provide comfort and durability for all-day wear. Perfect for layering or as a standalone statement piece, these wraps blend sophistication with everyday practicality.",
  },
  {
    _id: 1002,
    img: spfTwo,
    productName: "wraps Special",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Elevate your accessory game with our New Wraps Special a limited-edition upgrade to your everyday style. These premium wraps feature an exclusive diamond-weave fabric that resists wrinkles while maintaining exceptional softness. The hidden convertible design allows 5+ wearing styles (shawl, hood, scarf, or belt) with our signature no-slip grip technology. Each purchase includes a complimentary styling guide with looks curated by our fashion directors.",
  },
  {
    _id: 1003,
    img: spfThree,
    productName: "Smart Water",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Stay optimally hydrated with Smart Water the intelligent way to drink. Our eco-friendly smart bottle syncs with your fitness tracker to glow when it's time to hydrate and tracks your daily intake via app. The built-in fruit infuser and triple-filter system transform tap water into spa-quality infused water, while the ergonomic grip fits perfectly in car cup holders.",
  },
  {
    _id: 1004,
    img: spfFour,
    productName: "Smart Water",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Pure hydration redefined. Our premium Smart Water bottle features nano-filtration technology that removes 99.9% of impurities while enriching water with essential minerals. The solar-charging cap displays real-time hydration stats and syncs with health apps to optimize your water intake based on activity levels. Sleek aerospace-grade aluminum construction keeps liquids cold for 24 hours.",
  },
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Smart Watch",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Meet your 24/7 wellness partner the New Smart Watch packs flagship features at an unbelievable value. The 1.3 AMOLED display shows real-time stress levels with guided breathing exercises, while the 10-day battery life outlasts competitors. Sleep tracking now includes snoring detection and smart alarm functionality to wake you at the optimal sleep phase",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "smart Water",
    price: "180.00",
    color: "Gray",
    badge: false,
    des: "For connoisseurs of hydration tech the Smart Water Premium Edition features a NASA-inspired vortex filtration system that structures water molecules for enhanced absorption. The hand-blown glass interior maintains perfect pH balance, while the platinum-plated smart cap measures electrolyte levels and suggests optimal replenishment times based on your activity data from Apple Health/Google Fit.",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "smart watert hot",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Your intelligent thermos companion. This Smart Water Hot maintains precise temperatures (40-100°C) for 12+ hours with its vacuum-insulated stainless steel body. The smart lid vibrates when your drink reaches the ideal drinking temperature and alerts you via app if left unattended. Perfect for teas, soups, or baby formula.",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "wraps",
    price: "220.00",
    color: "Black",
    badge: false,
    des: " Crafted from premium fabric, they provide comfort and durability for all-day wear. Perfect for layering or as a standalone statement piece, these wraps blend sophistication with everyday practicality.",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "wraps",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "Make a bold impression with this vibrant Blue wrap. The rich, eye-catching hue adds a pop of color to any ensemble, while the soft, lightweight fabric ensures comfort and ease of movement. Ideal for those who love to stand out, this wrap is perfect for casual outings, beach days, or adding a playful touch to your look. A must-have for expressive fashion lovers.",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Smart water",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Elite hydration for minimalists. The Short Water carbon fiber bottle compresses to half its size when empty, yet holds 750ml. Patented graphene lining eliminates odors and enhances water's oxygen content. Includes a hidden compartment for electrolyte tablets and a built-in ring holder for secure carrying.",
  },
  {
    _id: 1011,
    img: newArrThree,
    productName: "smart watch",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "More than timekeeping. This Smart Watch features a blood oxygen monitor, menstrual cycle tracker, and built-in GPS for under $100. The 2-week battery life and military-grade durability make it ideal for adventurers. Customize with 100+ downloadable watch faces.",
  },
  {
    _id: 1012,
    img: newArrFour,
    productName: "smart water",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Essential hydration with brains. Our entry-level Smart Water bottle tracks consumption via LED progress rings and glows to remind you to drink. The anti-sweat silicone base and carabiner clip make it perfect for gym bags or backpacks. Filters chlorine while adding magnesium.",
  },
 
];
